### PR TITLE
Make trend plot interactive

### PR DESCRIPTION
**Pull request by boshek**
This PR is a draft to address #55. To do this I have ported the report to become a quarto doc rather than rmarkdown and then written the viz in javascript for more interactivity.

Because the way this is implemented, it needs to be served up via https rather than a local html file. So screenshots it is. Here is the default which sets the x-axes to extend to the last 120 days:

image

but we can slide to only look at the last ten days:

image

or look at the past 6 months:

image

Also included here is a tooltip which gives some specific info:

image

I have also updated the build table to include passing runs. Because this adds a significant amount of rows to the table, I've implemented some interactivity for the build table. This looks like this:

image

I am hoping that @raulcd or @assignUser can offer some thoughts on this change. 

TODO before merging this:
- ~revise the workflow to use quarto instead of rmarkdown~
- ~final tweaks to polish trend plot~
- ~implement any suggestions.~

### CODE REVIEW

**Comment by assignUser** [comment]
Looks cool, I assume it will work via http to (as we can't use ssl on the bucket) and just needs to be served via server?

**Comment by assignUser** [comment]
With the file from the last run in the PR (served via `python -m http.server 8000`) I was only able to go back to 1st of july, where your screenshots go  further back, is that intentional?

**Comment by boshek** [comment]
> With the file from the last run in the PR (served via `python -m http.server 8000`) I was only able to go back to 1st of july, where your screenshots go further back, is that intentional?

Sort of. The build was struggling with that data and I working on implementing the big huge error table differently with some interactivity and column filtering.

I've made this lookback window configurable here: https://github.com/boshek/crossbow/blob/b5aae8df7ec7c22e67d69f1dff4243158828c0a2/.github/workflows/nightly_dashboard.yml#L70

**Comment by assignUser** [comment]
Ah nice. We release every quarter so 3-4 months if that is workabe?

**Comment by boshek** [comment]
@assignUser I've made some changes and I think this is ready (at least for a review). Thanks for your feedback to this point!

**Review by assignUser — APPROVED** [review]
This looks great! the new filter/dropdown stuff :exploding_head:  Let's merge it and make sure that it also works via s3!

**Pull request merged**
